name: darttonconnect
description: Dart SDK for TON Connect. Use it to connect your app to TON wallets via TonConnect protocol.
version: 1.0.3
homepage: https://github.com/romanovichim/dartTonconnect

environment:
  sdk: '>=3.3.4 <4.0.0'

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
dependencies:
  flutter:
    sdk: flutter
  crypto: ^3.0.2
  hex: ^0.2.0
  http: ^1.2.1
  logger: ^2.3.0
  pinenacl: ^0.6.0
  universal_html: ^2.2.4
  shared_preferences: ^2.1.2
